version: '3.3'
services:
  media:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: media
    env_file:
      - .env
    volumes:
      - ./docker/data/images:/media/data/images
    ports:
      - 127.0.0.1:9295:9295
    entrypoint: ./media server